export * from "./institution-dialog/institution-dialog.component"
export * from "./dependency-dialog/dependency-dialog.component"
export * from "./personnel-dialog/personnel-dialog.component"
export * from "./officer-dialog/officer-dialog.component"
export * from "./account-dialog/account-dialog.component"
export * from "./type-procedure-dialog/type-procedure-dialog.component"